site_name: Ichicraft Boards - Release Notes
site_url: https://ichicraft.github.io/widgets-docs/
theme:
    name: material
    logo: images/logo.png
    favicon: images/favicon.png
extra_css:
    - styles/extra.css
extra_javascript:
    - scripts/script.js